language: go
go:
  - 1.4.3
install:
  - go get golang.org/x/crypto/blowfish
  - go get golang.org/x/crypto/cast5
  - go get golang.org/x/crypto/salsa20
  - go get github.com/codahale/chacha20
  - go get github.com/shadowsocks/shadowsocks-go/shadowsocks
  - go install ./mu
script:
  - PATH=$PATH:$HOME/gopath/bin bash -x ./script/test.sh
sudo: false